### PR TITLE
Es6/remove application

### PR DESCRIPTION
**Pull request by wwwtyro**

### CODE REVIEW

**Comment by wwwtyro** [comment]
Hi @ibgreen! Here's a little of what I've accomplished so far for removing the `Application` class. I've broken buffer handling out into its own class, `Buffer`, and gotten the first six lessons working with it. This is still a WIP (in particular some of the buffer creation in the lessons looks a little wonky because of their use of the `O3D.Model` class, but I think those will be cleaned up soon - either to stop using `Model` or to use `Scene` in the lessons), but you can at least see the direction I'm starting to take.

Next up is refactoring `Model` to use the new `Buffer` class.

I'm going to close this PR for now and reopen it when it's ready for a final review.

@philogb

**Comment by ibgreen** [comment]
@wwwtyro 
Thanks for the update. The direction is right, we definitely want to move the setBuffers method out of application.

Some food for thought: Wouldn't it be easier to just move the App.setBuffer functionality to the Program.setBuffer method rather than create the new Buffer class.

The reason I say this is that while I have only done a light review of your code, it seemed like the Buffer class' only reason for existence is as a one-time, temporary parameter to Program.setBuffer. 

If that's the case, it may be worth considering a change and just have Program.setBuffer take the params that the Buffer constructor takes and do the job in an internal helper method?

**Comment by wwwtyro** [comment]
Hey @ibgreen, I think the only issue with that approach is figuring out how to share buffers between programs. The Application class caches the buffers, so any program calling SetBuffer/s would have access to that cache. Doing away with Application means we lose the cache and push the management of the data to the user, which means we need some kind of buffer object for them to hold onto.

The same goes for all of the other objects the Application was managing. I'm all for it, since we will have the Model/Scene/etc abstractions to layer on top of them and abstract them away if the user wants to use a simpler API, while we (and more advanced users) can use the decoupled, modular, more flexible API underneath.

That said, if you can figure out some cleaner, cleverer way to do this, well, I'd be all over it! :D

**Comment by ibgreen** [comment]
Well, if the Program class is the only code that uses the shared buffers, then it is easy. The caches can just be static variables on the Program class. 
  class Program {
    setBuffer(buffer) {
      Program._buffers.push(buffer);
    }
  }

  Program._buffers = [];

If you need them in some other place, you could add a static method to get the buffers. Let me know

**Comment by wwwtyro** [comment]
Wouldn't that break multiple contexts?

**Comment by ibgreen** [comment]
OK I see. Resources cannot be shared between gl contexts, so a combined cache lookup could return a buffer that doesn't work with the current context.

Here's a couple of possible ways around that...

1) Look at Map and WeakMap in ES6. I think they can be keyed by arbitrary values, not just strings.

If so, having a `bufferCacheMap[gl].buffers` indexed by the gl context could be possible. We do get a garbage collection issue from these static maps, but I am not too worried about it. WeakMap might prevent it but I am not sure if it is supported on the browser, and it cannot be emulated by polyfills. Better start with Map and get everything properly debugged first.

2) - A slightly "hacky" approach could be to store the cache directly on the gl context.
```
gl.bufferCache = ...;
```
It theoretically risks some conflict with webGL implementation but should be the easiest to implement and good from a garbage collection perspective, no static objects that hold references to gl contexts, caches etc. As soon as the application clears the last reference to the context, it can be released, which can release the buffer cache etc.

3) - This one might be hard to determine on but have you looked at how important the buffer cache really is? 5+ years have probably passed since this code was written. Is it still a worthwhile optimization? If not just drop it?

**Comment by wwwtyro** [comment]
#3 is what I'm currently working towards, and honestly what I like the most of the three. Caches were never was an optimization here, just a paradigm for organizing the code - one that took some of the complexity away from the user in that they wouldn't have to hold onto buffer objects (they would use strings to reference the buffers instead). I also think it comes out a little cleaner than the other two.

**Comment by wwwtyro** [comment]
@ibgreen Here's tonight's work - refactoring model.js to use Buffer objects.

**Comment by wwwtyro** [comment]
@ibgreen 
Alright, this is more-or-less ready for a full review. Application is gone and all 16 lessons are working. There's a few straggling references to 'app' that aren't hit by the lessons, so I left them for cleanup when we get tests that touch them. The picking functions in the Scene object are an example. Cubemaps need to be added back in and are also in need of a test. I expect them to be fairly straightforward.

The major changes here are:

* Application is gone.
* a new Texture2D class (texture.js)
* a new Framebuffer class (fbo.js)
* Everything that took an app before just takes a gl context (if it needs it), with the exception of...
* Events just takes the canvas element you want to track events on

**Comment by ibgreen** [comment]
@wwwtyro Awesome, you got all the major structural changes in place. Merged.

**Comment by wwwtyro** [comment]
@ibgreen Thanks!

**Pull request merged**
