### PR TITLE
refactor lessons

### PR DESCRIPTION
**Pull request by wwwtyro**
@ibgreen @philogb 

Hey Ib, this refactors the lessons to always include the latest lesson code and modernize the layout a bit.

screenshot from 2016-01-25 22-07-28

### CODE REVIEW

**Comment by philogb** [comment]
That looks awesome @wwwtyro !

**Comment by wwwtyro** [comment]
Thanks @philogb! :grinning:

**Comment by ibgreen** [comment]
@wwwtyro Code looks awesome. I'll try it out during the day.

**Comment by wwwtyro** [comment]
Thanks! :)

**Pull request merged**
